---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: pajamadeals.in
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: solr_sunspot
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-48028060
  image_type: t2.micro
  image_id: ami-987724ca
  security_groups:
  - default
  - web
  - web_tools
  external_host: ec2-54-179-160-229.ap-southeast-1.compute.amazonaws.com
  external_ip: 54.179.160.229
  internal_host: ip-172-31-13-62.ap-southeast-1.compute.internal
  internal_ip: 172.31.13.62
  zone: ap-southeast-1a
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
